// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaDEyJPzx0Fgck6xKvHnpY_k4p7mSHYro',
    appId: '1:382798293847:web:5a942fa7cfd70203726c12',
    messagingSenderId: '382798293847',
    projectId: 'febbatch-9354b',
    authDomain: 'febbatch-9354b.firebaseapp.com',
    storageBucket: 'febbatch-9354b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE7AybjY7RWirbU4R5JE7btPjSdhpWtFo',
    appId: '1:382798293847:android:67fb79c0edeabfb8726c12',
    messagingSenderId: '382798293847',
    projectId: 'febbatch-9354b',
    storageBucket: 'febbatch-9354b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOZtl5gXtZRP5MnmCvE9XwgHD4xdyQJlI',
    appId: '1:382798293847:ios:b1380a33899ad2c7726c12',
    messagingSenderId: '382798293847',
    projectId: 'febbatch-9354b',
    storageBucket: 'febbatch-9354b.firebasestorage.app',
    iosBundleId: 'com.example.myFirstBc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOZtl5gXtZRP5MnmCvE9XwgHD4xdyQJlI',
    appId: '1:382798293847:ios:b1380a33899ad2c7726c12',
    messagingSenderId: '382798293847',
    projectId: 'febbatch-9354b',
    storageBucket: 'febbatch-9354b.firebasestorage.app',
    iosBundleId: 'com.example.myFirstBc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaDEyJPzx0Fgck6xKvHnpY_k4p7mSHYro',
    appId: '1:382798293847:web:c330bb74d894e8ae726c12',
    messagingSenderId: '382798293847',
    projectId: 'febbatch-9354b',
    authDomain: 'febbatch-9354b.firebaseapp.com',
    storageBucket: 'febbatch-9354b.firebasestorage.app',
  );
}
